import { ArrowRight, Radio } from "lucide-react";
import type { LiveRoom } from "@/lib/rooms";
import { SiteHeader } from "./SiteHeader";

function initials(room: LiveRoom) {
  return room.creator.split(/\s+/).map((word) => word[0]).join("").slice(0, 2).toUpperCase();
}

export function Browse({ rooms }: { rooms: LiveRoom[] }) {
  const featured = rooms[0];
  return <main className="browsePage"><SiteHeader/><div className="browseShell"><aside className="sideRail"><h3>LIVE CHANNELS</h3>{rooms.map((room, index)=><a href={`/live/${room.slug}`} key={room.slug}><span className={`miniAvatar accent-${index % 6}`}>{initials(room)}</span><span><b>{room.creator}</b><small>{room.name}</small></span><em><i/>{room.viewers}</em></a>)}</aside><section className="browseContent"><div className="welcome"><span><Radio size={14}/> LIVE ON UC8</span><h1>What&apos;s happening<br/><em>right now.</em></h1><p>You can use a tablet, or a landscape device for a better experience. Portrait is not recommended.</p></div>{featured ? <><a href={`/live/${featured.slug}`} className="featureRoom liveArtwork"><div className="featureCopy"><span className="livePill"><i/> LIVE</span><h2>{featured.name}</h2><div><span className="channelAvatar accent-0">{initials(featured)}</span><b>{featured.creator}</b><small>{featured.viewers} watching</small></div></div><span className="watchNow">Watch now <ArrowRight size={18}/></span></a><div className="sectionTitle"><div><span><Radio size={14}/> LIVE NOW</span><h2>All live rooms</h2></div><small>{rooms.length} {rooms.length === 1 ? "room" : "rooms"} live</small></div><div className="roomGrid">{rooms.slice(1).map((room,index)=><a href={`/live/${room.slug}`} className="roomTile" key={room.slug}><div className="roomArt liveArtwork"><span className="livePill"><i/> LIVE</span><span className="viewerCount">{room.viewers} watching</span><div className="artMonogram">{initials(room)}</div></div><div className="roomInfo"><span className={`miniAvatar accent-${(index+1)%6}`}>{initials(room)}</span><div><h3>{room.name}</h3><p>{room.creator}</p></div></div></a>)}</div></> : <div className="emptyRooms"><Radio size={28}/><h2>No one is live yet</h2><p>Active LiveKit broadcasts will appear here automatically.</p><a className="goLive" href="/creator/live">Start a broadcast</a></div>}</section></div><footer><span>© 2026 uc8Live</span><span>Real people. Right now.</span><span>Community guidelines · Privacy</span></footer></main>;
}
