"use client";
import { FormEvent, useState } from "react";
import { LiveKitRoom, RoomAudioRenderer, VideoConference } from "@livekit/components-react";
import "@livekit/components-styles";
import { ArrowLeft, Eye, KeyRound, LockKeyhole, Radio, ShieldCheck, Sparkles } from "lucide-react";
import { rooms } from "@/lib/rooms";

export function CreatorStudio(){const [code,setCode]=useState("");const [room,setRoom]=useState(rooms[0].slug);const [connection,setConnection]=useState<{token:string,url:string}|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 async function enter(e:FormEvent){e.preventDefault();setLoading(true);setError("");const r=await fetch("/api/token",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role:"creator",code,room})});const d=await r.json();setLoading(false);d.token?setConnection(d):setError(d.error)}
 if(connection)return <main className="studio"><header><BrandInline/><a href="/live/"><Eye size={17}/> Watch live</a></header><section className="studioRoom"><div className="studioTitle"><div><span className="eyebrow"><Radio size={14}/> CREATOR STUDIO</span><h1>You’re in the studio.</h1><p>Allow camera and microphone access, then publish when you’re ready.</p></div><span className="secure"><ShieldCheck size={17}/> Secure room</span></div><LiveKitRoom token={connection.token} serverUrl={connection.url} connect audio video className="creatorRoom"><VideoConference/><RoomAudioRenderer/></LiveKitRoom></section></main>;
 return <main className="loginPage"><div className="grain"/><header><BrandInline/><a href="/live/"><ArrowLeft size={16}/> Back to browse</a></header><section className="loginWrap"><div className="loginIntro"><span className="eyebrow"><Sparkles size={14}/> CREATOR ACCESS</span><h1>Your room.<br/><em>Your moment.</em></h1><p>Step behind the camera and share what’s happening — live, unfiltered, and entirely yours.</p><div className="feature"><span><Radio/></span><div><b>Broadcast in real time</b><p>Choose a room, then publish with LiveKit.</p></div></div><div className="feature"><span><ShieldCheck/></span><div><b>A space with intention</b><p>Device protection keeps your community human.</p></div></div></div><form className="codeCard" onSubmit={enter}><div className="keyIcon"><KeyRound/></div><h2>Enter the studio</h2><p>Creator access is invite-only.<br/>Choose your room and enter your code.</p><label>LIVE ROOM</label><select value={room} onChange={e=>setRoom(e.target.value)}>{rooms.map(r=><option value={r.slug} key={r.slug}>{r.creator} — {r.title}</option>)}</select><label>CREATOR CODE</label><div className="codeInput"><LockKeyhole size={18}/><input autoFocus value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="UC8-••••-••••"/></div>{error&&<div className="formError">{error}</div>}<button disabled={!code||loading}>{loading?"Checking…":"Continue to studio"}<span>→</span></button><small><ShieldCheck size={13}/> Protected by device-level abuse prevention</small></form></section><footer><span>© 2026 uc8Live</span><span>Need a creator code? <b>Request access</b></span></footer></main>}
function BrandInline(){return <a href="/live/" className="brand"><span className="brandMark"><i/><i/><i/></span><b>uc8</b>Live</a>}
