"use client";
import { FormEvent, useState } from "react";
import { LiveKitRoom, RoomAudioRenderer, VideoConference } from "@livekit/components-react";
import "@livekit/components-styles";
import { ArrowLeft, Eye, KeyRound, LockKeyhole, Radio, ShieldCheck, Sparkles } from "lucide-react";

type CreatorAction="create"|"join";
export function CreatorStudio(){const [code,setCode]=useState("");const [room,setRoom]=useState("");const [action,setAction]=useState<CreatorAction>("create");const [connection,setConnection]=useState<{token:string,url:string;participantRole:"host"|"guest_creator"}|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 async function enter(e:FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/token",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({role:"creator",action,code,room})});const d=await r.json();d.token?setConnection(d):setError(d.error)}catch{setError("Unable to reach the studio. Try again.")}finally{setLoading(false)}}
 if(connection){const guest=connection.participantRole==="guest_creator";return <main className="studio"><header><BrandInline/><a href="/live/"><Eye size={17}/> Watch live</a></header><section className="studioRoom"><div className="studioTitle"><div><span className="eyebrow"><Radio size={14}/> CREATOR STUDIO</span><h1>{guest?"You’ve joined the room.":"You’re live in your room."}</h1><p>{guest?"You can publish your camera and microphone alongside the host.":"Allow camera and microphone access, then publish when you’re ready."}</p></div><span className="secure"><ShieldCheck size={17}/> Secure room</span></div><LiveKitRoom token={connection.token} serverUrl={connection.url} connect audio video className="creatorRoom"><VideoConference/><RoomAudioRenderer/></LiveKitRoom></section></main>}
 return <main className="loginPage"><div className="grain"/><header><BrandInline/><a href="/live/"><ArrowLeft size={16}/> Back to browse</a></header><section className="loginWrap"><div className="loginIntro"><span className="eyebrow"><Sparkles size={14}/> CREATOR ACCESS</span><h1>Your room.<br/><em>Your moment.</em></h1><p>Start a new room or join another creator in an existing broadcast.</p><div className="feature"><span><Radio/></span><div><b>Broadcast in real time</b><p>Creators publish camera and microphone with LiveKit.</p></div></div><div className="feature"><span><ShieldCheck/></span><div><b>Invite-only access</b><p>Your creator code is validated securely on the server.</p></div></div></div><form className="codeCard" onSubmit={enter}><div className="actionTabs" role="tablist"><button type="button" className={action==="create"?"active":""} onClick={()=>{setAction("create");setError("")}}>Start Room</button><button type="button" className={action==="join"?"active":""} onClick={()=>{setAction("join");setError("")}}>Join Room</button></div><div className="keyIcon"><KeyRound/></div><h2>{action==="create"?"Start Room":"Join Room"}</h2><p>{action==="create"?"Create a new uc8Live broadcast.":"Join an existing uc8Live room as another creator."}</p><label>{action==="create"?"NEW ROOM NAME":"EXISTING ROOM NAME"}</label><div className="codeInput"><Radio size={18}/><input value={room} onChange={e=>setRoom(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,63))} placeholder="my-live-room"/></div><label className="creatorCodeLabel">CREATOR CODE</label><div className="codeInput"><LockKeyhole size={18}/><input type="password" autoComplete="off" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="UC8-••••-••••"/></div>{error&&<div className="formError">{error}</div>}<button disabled={!room||!code||loading}>{loading?"Checking…":action==="create"?"Start broadcasting":"Join room"}<span>→</span></button><small><ShieldCheck size={13}/> Protected by device-level abuse prevention</small></form></section><footer><span>© 2026 uc8Live</span><span>Creator access is invite-only</span></footer></main>}
function BrandInline(){return <a href="/live/" className="brand"><span className="brandMark"><i/><i/><i/></span><b>uc8</b>Live</a>}
