export type Role = 'viewer' | 'creator' | 'admin'
export type Visibility = 'public' | 'unlisted' | 'private'
export type StreamStatus = 'offline' | 'connecting' | 'live' | 'reconnecting' | 'disabled' | 'error'
export interface Database { public: { Tables: {
  profiles: { Row: { id:string; display_name:string; username:string; avatar_url:string|null; bio:string; role:Role; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['profiles']['Row']> & {id:string;display_name:string;username:string}; Update: Partial<Database['public']['Tables']['profiles']['Row']>; Relationships: [] }
  live_channels: { Row: { id:string; owner_id:string; slug:string; title:string; description:string; category:string; thumbnail_url:string|null; visibility:Visibility; mux_live_stream_id:string; mux_playback_id:string; mux_stream_status:StreamStatus; is_enabled:boolean; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['live_channels']['Row']> & {owner_id:string;slug:string;title:string;mux_live_stream_id:string;mux_playback_id:string}; Update: Partial<Database['public']['Tables']['live_channels']['Row']>; Relationships: [] }
  broadcasts: { Row: { id:string; channel_id:string; mux_asset_id:string|null; mux_playback_id:string|null; title:string; started_at:string; ended_at:string|null; status:string; duration_seconds:number|null; is_replay_public:boolean; created_at:string; updated_at:string }; Insert: Partial<Database['public']['Tables']['broadcasts']['Row']> & {channel_id:string;title:string}; Update: Partial<Database['public']['Tables']['broadcasts']['Row']>; Relationships: [] }
  mux_webhook_events: { Row: { id:string; mux_event_id:string; event_type:string; processed_at:string|null; payload:unknown; processing_status:string; error_message:string|null }; Insert: Partial<Database['public']['Tables']['mux_webhook_events']['Row']> & {mux_event_id:string;event_type:string;payload:unknown}; Update: Partial<Database['public']['Tables']['mux_webhook_events']['Row']>; Relationships: [] }
} } }
