import { useCallback,useEffect,useState } from 'react'
import { BadgeCheck,ExternalLink,ShieldCheck } from 'lucide-react'
import { authenticatedFetch } from '@/client/auth'
import { CreatorShell } from './CreatorShell'

type Status={status:string;ageVerified:boolean;verifiedAt:string|null}
export function IdentityVerification(){
  const [status,setStatus]=useState<Status>();const [busy,setBusy]=useState(false);const [error,setError]=useState('')
  const refresh=useCallback(async()=>{const response=await authenticatedFetch('/api/identity/session');if(response.status===401){location.assign('/login');return}if(!response.ok)throw new Error('Verification status could not be loaded.');setStatus(await response.json())},[])
  useEffect(()=>{refresh().catch(error=>setError(error instanceof Error?error.message:'Verification status could not be loaded.'))},[refresh])
  async function start(){setBusy(true);setError('');try{const response=await authenticatedFetch('/api/identity/session',{method:'POST'});if(!response.ok)throw new Error((await response.json()).error??'Verification could not be started.');const {verificationUrl}=await response.json();const {DiditSdk}=await import('@didit-protocol/sdk-web');const sdk=DiditSdk.shared;sdk.onComplete=()=>{setBusy(false);void refresh()};await sdk.startVerification({url:verificationUrl,configuration:{showCloseButton:true,showExitConfirmation:true,closeModalOnComplete:true}})}catch(error){setBusy(false);setError(error instanceof Error?error.message:'Verification could not be started.') }}
  return <CreatorShell><div className="pageTitle"><div><span className="eyebrow">IDENTITY</span><h1>Age verification</h1><p>Verify that you are at least 18 before your channel can stream.</p></div></div><section className="verificationCard"><div className={`verificationIcon ${status?.ageVerified?'verified':''}`}>{status?.ageVerified?<BadgeCheck/>:<ShieldCheck/>}</div><div><span className="eyebrow">{status?.ageVerified?'VERIFIED':'STREAMING REQUIREMENT'}</span><h2>{status?.ageVerified?'You are cleared to stream':'Confirm your age securely'}</h2><p>{status?.ageVerified?'Your identity check is complete. You can enable your channel and reveal your OBS credentials.':'Didit securely handles document capture and identity checks. uc8Live stores only your verification status and calculated age—not document images or identity details.'}</p>{status&&!status.ageVerified&&status.status!=='not_started'&&<div className="notice">Current status: <b>{status.status.replaceAll('_',' ')}</b>. Final decisions arrive securely by webhook.</div>}{error&&<div className="error">{error}</div>}{!status?.ageVerified&&<button className="primary" disabled={busy} onClick={start}>{busy?'Opening verification…':'Verify with Didit'} <ExternalLink/></button>}</div></section></CreatorShell>
}
