/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as CreatorBroadcastsRouteImport } from './routes/creator/broadcasts'
import { Route as CreatorChannelRouteImport } from './routes/creator/channel'
import { Route as CreatorSettingsRouteImport } from './routes/creator/settings'
import { Route as CreatorStreamRouteImport } from './routes/creator/stream'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as LiveChannelSlugRouteImport } from './routes/live/$channelSlug'
import { Route as ApiBroadcastsBroadcastIdRouteImport } from './routes/api/broadcasts/$broadcastId'
import { Route as ApiChannelsIndexRouteImport } from './routes/api/channels/index'
import { Route as ApiChannelsCredentialsRouteImport } from './routes/api/channels/credentials'
import { Route as ApiChannelsEnabledRouteImport } from './routes/api/channels/enabled'
import { Route as ApiChannelsMineRouteImport } from './routes/api/channels/mine'
import { Route as ApiWebhooksMuxRouteImport } from './routes/api/webhooks/mux'
import { Route as ApiPublicChannelSlugRouteImport } from './routes/api/public/channel/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/creator/',
  path: '/creator/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorBroadcastsRoute = CreatorBroadcastsRouteImport.update({
  id: '/creator/broadcasts',
  path: '/creator/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorChannelRoute = CreatorChannelRouteImport.update({
  id: '/creator/channel',
  path: '/creator/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/creator/settings',
  path: '/creator/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStreamRoute = CreatorStreamRouteImport.update({
  id: '/creator/stream',
  path: '/creator/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveChannelSlugRoute = LiveChannelSlugRouteImport.update({
  id: '/live/$channelSlug',
  path: '/live/$channelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBroadcastsBroadcastIdRoute =
  ApiBroadcastsBroadcastIdRouteImport.update({
    id: '/api/broadcasts/$broadcastId',
    path: '/api/broadcasts/$broadcastId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChannelsIndexRoute = ApiChannelsIndexRouteImport.update({
  id: '/api/channels/',
  path: '/api/channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsCredentialsRoute = ApiChannelsCredentialsRouteImport.update({
  id: '/api/channels/credentials',
  path: '/api/channels/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsEnabledRoute = ApiChannelsEnabledRouteImport.update({
  id: '/api/channels/enabled',
  path: '/api/channels/enabled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsMineRoute = ApiChannelsMineRouteImport.update({
  id: '/api/channels/mine',
  path: '/api/channels/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMuxRoute = ApiWebhooksMuxRouteImport.update({
  id: '/api/webhooks/mux',
  path: '/api/webhooks/mux',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChannelSlugRoute = ApiPublicChannelSlugRouteImport.update({
  id: '/api/public/channel/$slug',
  path: '/api/public/channel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/config': typeof ApiConfigRoute
  '/creator/broadcasts': typeof CreatorBroadcastsRoute
  '/creator/channel': typeof CreatorChannelRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/stream': typeof CreatorStreamRoute
  '/live/$channelSlug': typeof LiveChannelSlugRoute
  '/creator/': typeof CreatorIndexRoute
  '/live/': typeof LiveIndexRoute
  '/api/broadcasts/$broadcastId': typeof ApiBroadcastsBroadcastIdRoute
  '/api/channels/credentials': typeof ApiChannelsCredentialsRoute
  '/api/channels/enabled': typeof ApiChannelsEnabledRoute
  '/api/channels/mine': typeof ApiChannelsMineRoute
  '/api/webhooks/mux': typeof ApiWebhooksMuxRoute
  '/api/channels/': typeof ApiChannelsIndexRoute
  '/api/public/channel/$slug': typeof ApiPublicChannelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/config': typeof ApiConfigRoute
  '/creator/broadcasts': typeof CreatorBroadcastsRoute
  '/creator/channel': typeof CreatorChannelRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/stream': typeof CreatorStreamRoute
  '/live/$channelSlug': typeof LiveChannelSlugRoute
  '/creator': typeof CreatorIndexRoute
  '/live': typeof LiveIndexRoute
  '/api/broadcasts/$broadcastId': typeof ApiBroadcastsBroadcastIdRoute
  '/api/channels/credentials': typeof ApiChannelsCredentialsRoute
  '/api/channels/enabled': typeof ApiChannelsEnabledRoute
  '/api/channels/mine': typeof ApiChannelsMineRoute
  '/api/webhooks/mux': typeof ApiWebhooksMuxRoute
  '/api/channels': typeof ApiChannelsIndexRoute
  '/api/public/channel/$slug': typeof ApiPublicChannelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/config': typeof ApiConfigRoute
  '/creator/broadcasts': typeof CreatorBroadcastsRoute
  '/creator/channel': typeof CreatorChannelRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/stream': typeof CreatorStreamRoute
  '/live/$channelSlug': typeof LiveChannelSlugRoute
  '/creator/': typeof CreatorIndexRoute
  '/live/': typeof LiveIndexRoute
  '/api/broadcasts/$broadcastId': typeof ApiBroadcastsBroadcastIdRoute
  '/api/channels/credentials': typeof ApiChannelsCredentialsRoute
  '/api/channels/enabled': typeof ApiChannelsEnabledRoute
  '/api/channels/mine': typeof ApiChannelsMineRoute
  '/api/webhooks/mux': typeof ApiWebhooksMuxRoute
  '/api/channels/': typeof ApiChannelsIndexRoute
  '/api/public/channel/$slug': typeof ApiPublicChannelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/config'
    | '/creator/broadcasts'
    | '/creator/channel'
    | '/creator/settings'
    | '/creator/stream'
    | '/live/$channelSlug'
    | '/creator/'
    | '/live/'
    | '/api/broadcasts/$broadcastId'
    | '/api/channels/credentials'
    | '/api/channels/enabled'
    | '/api/channels/mine'
    | '/api/webhooks/mux'
    | '/api/channels/'
    | '/api/public/channel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/config'
    | '/creator/broadcasts'
    | '/creator/channel'
    | '/creator/settings'
    | '/creator/stream'
    | '/live/$channelSlug'
    | '/creator'
    | '/live'
    | '/api/broadcasts/$broadcastId'
    | '/api/channels/credentials'
    | '/api/channels/enabled'
    | '/api/channels/mine'
    | '/api/webhooks/mux'
    | '/api/channels'
    | '/api/public/channel/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/api/config'
    | '/creator/broadcasts'
    | '/creator/channel'
    | '/creator/settings'
    | '/creator/stream'
    | '/live/$channelSlug'
    | '/creator/'
    | '/live/'
    | '/api/broadcasts/$broadcastId'
    | '/api/channels/credentials'
    | '/api/channels/enabled'
    | '/api/channels/mine'
    | '/api/webhooks/mux'
    | '/api/channels/'
    | '/api/public/channel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiConfigRoute: typeof ApiConfigRoute
  CreatorBroadcastsRoute: typeof CreatorBroadcastsRoute
  CreatorChannelRoute: typeof CreatorChannelRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorStreamRoute: typeof CreatorStreamRoute
  LiveChannelSlugRoute: typeof LiveChannelSlugRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ApiBroadcastsBroadcastIdRoute: typeof ApiBroadcastsBroadcastIdRoute
  ApiChannelsCredentialsRoute: typeof ApiChannelsCredentialsRoute
  ApiChannelsEnabledRoute: typeof ApiChannelsEnabledRoute
  ApiChannelsMineRoute: typeof ApiChannelsMineRoute
  ApiWebhooksMuxRoute: typeof ApiWebhooksMuxRoute
  ApiChannelsIndexRoute: typeof ApiChannelsIndexRoute
  ApiPublicChannelSlugRoute: typeof ApiPublicChannelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/': {
      id: '/creator/'
      path: '/creator'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/broadcasts': {
      id: '/creator/broadcasts'
      path: '/creator/broadcasts'
      fullPath: '/creator/broadcasts'
      preLoaderRoute: typeof CreatorBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/channel': {
      id: '/creator/channel'
      path: '/creator/channel'
      fullPath: '/creator/channel'
      preLoaderRoute: typeof CreatorChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/creator/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/stream': {
      id: '/creator/stream'
      path: '/creator/stream'
      fullPath: '/creator/stream'
      preLoaderRoute: typeof CreatorStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$channelSlug': {
      id: '/live/$channelSlug'
      path: '/live/$channelSlug'
      fullPath: '/live/$channelSlug'
      preLoaderRoute: typeof LiveChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/broadcasts/$broadcastId': {
      id: '/api/broadcasts/$broadcastId'
      path: '/api/broadcasts/$broadcastId'
      fullPath: '/api/broadcasts/$broadcastId'
      preLoaderRoute: typeof ApiBroadcastsBroadcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/': {
      id: '/api/channels/'
      path: '/api/channels'
      fullPath: '/api/channels/'
      preLoaderRoute: typeof ApiChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/credentials': {
      id: '/api/channels/credentials'
      path: '/api/channels/credentials'
      fullPath: '/api/channels/credentials'
      preLoaderRoute: typeof ApiChannelsCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/enabled': {
      id: '/api/channels/enabled'
      path: '/api/channels/enabled'
      fullPath: '/api/channels/enabled'
      preLoaderRoute: typeof ApiChannelsEnabledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/mine': {
      id: '/api/channels/mine'
      path: '/api/channels/mine'
      fullPath: '/api/channels/mine'
      preLoaderRoute: typeof ApiChannelsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mux': {
      id: '/api/webhooks/mux'
      path: '/api/webhooks/mux'
      fullPath: '/api/webhooks/mux'
      preLoaderRoute: typeof ApiWebhooksMuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channel/$slug': {
      id: '/api/public/channel/$slug'
      path: '/api/public/channel/$slug'
      fullPath: '/api/public/channel/$slug'
      preLoaderRoute: typeof ApiPublicChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiConfigRoute: ApiConfigRoute,
  CreatorBroadcastsRoute: CreatorBroadcastsRoute,
  CreatorChannelRoute: CreatorChannelRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorStreamRoute: CreatorStreamRoute,
  LiveChannelSlugRoute: LiveChannelSlugRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  ApiBroadcastsBroadcastIdRoute: ApiBroadcastsBroadcastIdRoute,
  ApiChannelsCredentialsRoute: ApiChannelsCredentialsRoute,
  ApiChannelsEnabledRoute: ApiChannelsEnabledRoute,
  ApiChannelsMineRoute: ApiChannelsMineRoute,
  ApiWebhooksMuxRoute: ApiWebhooksMuxRoute,
  ApiChannelsIndexRoute: ApiChannelsIndexRoute,
  ApiPublicChannelSlugRoute: ApiPublicChannelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
