create extension if not exists pgcrypto;
create type public.user_role as enum ('viewer','creator','admin');
create type public.channel_visibility as enum ('public','unlisted','private');
create type public.stream_status as enum ('offline','connecting','live','reconnecting','disabled','error');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text not null,username text not null unique check(username ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),avatar_url text,bio text not null default '',role user_role not null default 'creator',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.live_channels(id uuid primary key default gen_random_uuid(),owner_id uuid not null unique references profiles(id) on delete cascade,slug text not null unique check(slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),title text not null,description text not null default '',category text not null,thumbnail_url text,visibility channel_visibility not null default 'public',mux_live_stream_id text not null unique,mux_playback_id text not null,mux_stream_status stream_status not null default 'offline',is_enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.broadcasts(id uuid primary key default gen_random_uuid(),channel_id uuid not null references live_channels(id) on delete cascade,mux_asset_id text unique,mux_playback_id text,title text not null,started_at timestamptz not null default now(),ended_at timestamptz,status text not null default 'live' check(status in ('live','processing','ready','error')),duration_seconds integer,is_replay_public boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.mux_webhook_events(id uuid primary key default gen_random_uuid(),mux_event_id text not null unique,event_type text not null,processed_at timestamptz,payload jsonb not null,processing_status text not null default 'processing',error_message text);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,display_name,username,role) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)),coalesce(new.raw_user_meta_data->>'username',replace(new.id::text,'-','')),'creator');return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table profiles enable row level security;alter table live_channels enable row level security;alter table broadcasts enable row level security;alter table mux_webhook_events enable row level security;
create policy "profiles public read" on profiles for select using(true);create policy "profile self update" on profiles for update using(auth.uid()=id) with check(auth.uid()=id);
create policy "public channel read" on live_channels for select using(visibility='public' or (visibility='unlisted') or auth.uid()=owner_id);create policy "owner channel write" on live_channels for all using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
create policy "public replay read" on broadcasts for select using(is_replay_public or exists(select 1 from live_channels c where c.id=channel_id and c.owner_id=auth.uid()));create policy "owner broadcast write" on broadcasts for all using(exists(select 1 from live_channels c where c.id=channel_id and c.owner_id=auth.uid())) with check(exists(select 1 from live_channels c where c.id=channel_id and c.owner_id=auth.uid()));
-- No client policy exists for webhook events; only the service role can access them.
